<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QLPG_a</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\DiemHocPhan\**" />
    <Content Remove="Views\DiemHocPhan\**" />
    <EmbeddedResource Remove="Views\DiemHocPhan\**" />
    <None Remove="Views\DiemHocPhan\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\DiemHocPhanController.cs" />
    <Compile Remove="Models\DiemHocPhan.cs" />
    <Compile Remove="Models\HocPhan.cs" />
    <Compile Remove="Models\LopHoc.cs" />
    <Compile Remove="Models\MonHoc.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\NewFolder\" />
  </ItemGroup>

</Project>
